---
- hosts: all

  pre_tasks:
    - name: Check if Website essentials are installed
      shell: "nginx -v && npm -v && git --version"
      register: website_essentials
      ignore_errors: true

    - name: Set Website installed fact
      set_fact:
        website_installed: "{{ website_essentials.rc == 0 }}"

    - name: Install the Website essentials if not installed
      include_tasks: essentials/website.yaml
      when: not website_installed
    
    - name: Force update
      include_tasks: essentials/website.yaml
      when: "website_installed and {{ force_update }} == true"

  tasks:
    - name: "Clone the website repository"
      git:
          repo: "https://github.com/Kostas-Xafis/DtstProjectFrontend.git"
          dest: "{{ frontend_app_dir }}"
          version: "{{ branch }}"
          force: true

    - name: "Install dependencies & Build the website"
      shell: "export PATH=$PATH:~/.nvm/versions/node/v20.12.1/bin ; npm install ; npm run build"
      args:
        chdir: "{{ frontend_app_dir }}"
    
    - name: "Replace VITE_BACKEND_URL in .env"
      lineinfile:
        path: "{{ frontend_app_dir }}/.env"
        regexp: "^VITE_BACKEND_URL="
        line: "VITE_BACKEND_URL=http://{{ backend_server_host }}:{{ backend_server_port }}/"
        state: present
        create: true

    - name: "Copy dist in nginx location" 
      copy:
        src: "{{ frontend_app_dir }}/dist/"
        dest: "{{ site_location }}"
        remote_src: true
        mode: 7777
        force: true
      notify: restart nginx
      become: true

    - name: "Copy nginx conf file"
      template:
        src: ../files/nginx.frontend.j2
        dest: "/etc/nginx/sites-available/website"
      notify: restart nginx
      become: true

    - name: "Enable website in nginx"
      file:
        src: "/etc/nginx/sites-available/website"
        dest: "/etc/nginx/sites-enabled/website"
        state: link
      notify: restart nginx
      become: true
    
    - name: "De-activate default nginx site"
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: true
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: true